[tools]
hugo-extended = "0.146.4"

[tasks."server:preview"]
description = "Elindítja a local szervert és megnyitja az oldalt böngészőben"
run         = "hugo server --buildDrafts --buildExpired --buildFuture --navigateToChanged --openBrowser"

[tasks."server:nodrafts"]
description = "Elindítja a local szervert és megnyitja az oldalt böngészőben"
run         = "hugo server --navigateToChanged --openBrowser"

[tasks."publish:clean"]
description = "Előkészíti a kézi publikációt"
run = "rm -rf public && git clone git@github.com:neilus/kari-blog.git public && cd public && git checkout gh-pages"
hide = true

[tasks."publish:build"]
description = "Legyártja a forrás fájlokból a weboldalt"
run         = "hugo build --minify"
hide        = true
sources     = ['mise.toml', 'hugo.toml', 'archetypes', 'assets', 'content', 'data', 'i18n', 'resources', 'static', 'themes']
outputs     = ['public/*.html']

[tasks."publish:kezi-publikalas"]
description = "Kezzel publikalja az oldalt"
run         = "cd public && git add . && git commit -m 'kézi vezérlés' && git push"
depends     = ["publish:build" ]
hide      = true
