[tools]
hugo-extended = "0.146.4"

[tasks."server:preview"]
description = "Elindítja a local szervert és megnyitja az oldalt böngészőben"
run         = "hugo server --buildDrafts --buildExpired --buildFuture --navigateToChanged --openBrowser"

[tasks."server:nodrafts"]
description = "Elindítja a local szervert és megnyitja az oldalt böngészőben"
run         = "hugo server --navigateToChanged --openBrowser"

[tasks."publish:build"]
description = "Legyártja a forrás fájlokból a weboldalt"
run         = "hugo build --minify"
outputs     = ['public/']
hide      = true
